frame_data = [
    {'frame':'6B',
     'stage':['1', '2', '3', '4', 'T1', 'T2', 'T3'],
     'position':{'1':['TOP', 'RIGHT', 'BOTTOM', 'LEFT'],
                 '2':['TOP', 'RIGHT', 'BOTTOM', 'LEFT'],
                 '3':['TOP', 'RIGHT', 'BOTTOM', 'LEFT'],
                 '4':['TOP', 'RIGHT', 'BOTTOM', 'LEFT'],
                 'T1':['TOP', 'RIGHT', 'BOTTOM', 'LEFT'],
                 'T2':['TOP', 'RIGHT', 'BOTTOM', 'LEFT'],
                 'T3':['TOP', 'RIGHT', 'BOTTOM', 'LEFT']},
     'spacer':{'1':'0.0',
               '2':'0.0',
               '3':'0.0',
               '4':'0.0',
               'T1':'1.1',
               'T2':'2.2',
               'T3':'3.3'}},
    {'frame':'6FA',
     'stage':['1', '2', '3', '4'],
     'position':{'1':['TOP', 'RIGHT', 'BOTTOM', 'LEFT'],
                 '2':['TOP', 'RIGHT', 'BOTTOM', 'LEFT'],
                 '3':['TOP', 'RIGHT', 'BOTTOM', 'LEFT'],
                 '4':['TOP', 'RIGHT', 'BOTTOM', 'LEFT']},
     'spacer':{'1':'0.0',
               '2':'0.0',
               '3':'0.0',
               '4':'0.0'}},
    {'frame':'7E',
     'stage':['1', '2', '3', '4'],
     'position':{'1':['TOP', 'RIGHT', 'BOTTOM', 'LEFT'],
                 '2':['TOP', 'RIGHT', 'BOTTOM', 'LEFT'],
                 '3':['TOP', 'RIGHT', 'BOTTOM', 'LEFT'],
                 '4':['TOP', 'RIGHT', 'BOTTOM', 'LEFT']},
     'spacer':{'1':'0.0',
               '2':'0.0',
               '3':'0.0',
               '4':'0.0'}},
    {'frame':'7FA',
     'stage':['1', '2', '3', '4'],
     'position':{'1':['TOP', 'RIGHT', 'BOTTOM', 'LEFT'],
                 '2':['TOP', 'RIGHT', 'BOTTOM', 'LEFT'],
                 '3':['TOP', 'RIGHT', 'BOTTOM', 'LEFT'],
                 '4':['TOP', 'RIGHT', 'BOTTOM', 'LEFT']},
     'spacer':{'1':'0.0',
               '2':'0.0',
               '3':'0.0',
               '4':'0.0'}},
    {'frame':'7FA.05',
     'stage':['1', '2', '3', '4'],
     'position':{'1':['TOP', 'TOP RIGHT', 'BOTTOM RIGHT', 'BOTTOM', 'BOTTOM LEFT', 'TOP LEFT'],
                 '2':['TOP', 'RIGHT', 'BOTTOM', 'LEFT'],
                 '3':['TOP', 'RIGHT', 'BOTTOM', 'LEFT'],
                 '4':['TOP', 'RIGHT', 'BOTTOM', 'LEFT']},
     'spacer':{'1':'0.0',
               '2':'0.0',
               '3':'0.0',
               '4':'0.0'}},
    {'frame':'9E',
     'stage':['1', '2', '3', '4'],
     'position':{'1':['TOP', 'RIGHT', 'BOTTOM', 'LEFT'],
                 '2':['TOP', 'RIGHT', 'BOTTOM', 'LEFT'],
                 '3':['TOP', 'RIGHT', 'BOTTOM', 'LEFT'],
                 '4':['TOP', 'RIGHT', 'BOTTOM', 'LEFT']},
     'spacer':{'1':'0.0',
               '2':'0.0',
               '3':'0.0',
               '4':'0.0'}},
    {'frame':'LMS',
     'stage':['1', '2', '3', '4'],
     'position':{'1':['TOP', 'RIGHT', 'BOTTOM', 'LEFT'],
                 '2':['TOP', 'RIGHT', 'BOTTOM', 'LEFT'],
                 '3':['TOP', 'RIGHT', 'BOTTOM', 'LEFT'],
                 '4':['TOP', 'RIGHT', 'BOTTOM', 'LEFT']},
     'spacer':{'1':'0.0',
               '2':'0.0',
               '3':'0.0',
               '4':'0.0'}},
    {'frame':'7HA',
     'stage':['1', '2', '3', '4'],
     'position':{'1':['TOP', 'RIGHT', 'BOTTOM', 'LEFT'],
                 '2':['TOP', 'RIGHT', 'BOTTOM', 'LEFT'],
                 '3':['TOP', 'RIGHT', 'BOTTOM', 'LEFT'],
                 '4':['TOP', 'RIGHT', 'BOTTOM', 'LEFT']},
     'spacer':{'1':'0.0',
               '2':'0.0',
               '3':'0.0',
               '4':'0.0'}},
    {'frame':'9HA',
     'stage':['1', '6', '11', '14'],
     'position':{'1':['TOP', 'RIGHT', 'BOTTOM', 'LEFT'],
                 '6':['TOP', 'RIGHT', 'BOTTOM', 'LEFT'],
                 '11':['TOP', 'RIGHT', 'BOTTOM', 'LEFT'],
                 '14':['TOP', 'RIGHT', 'BOTTOM', 'LEFT']},
     'spacer':{'1':'0.0',
               '2':'0.0',
               '3':'0.0',
               '4':'0.0'}}
];
